export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const SET_USER = 'SET_USER'

export const SET_CARS = 'SET_CARS'
export const SET_CAR = 'SET_CAR'
export const SET_DETAILS = 'SET_DETAILS'
export const ADD_CAR = 'ADD_CAR'
export const REMOVE_CAR = 'REMOVE_CAR'

export const SET_FAMILIES = 'SET_FAMILIES'
export const SET_FAMILY = 'SET_FAMILY'
export const ADD_FAMILY = 'ADD_FAMILY'
export const REMOVE_FAMILY = 'REMOVE_FAMILY'
export const EDIT_FAMILY = 'EDIT_FAMILY'
export const SET_FAMILY_CARS = 'SET_FAMILY_CARS'
export const ADD_FAMILY_CAR = 'ADD_FAMILY_CAR'
export const EDIT_FAMILY_CAR = 'EDIT_FAMILY_CAR'
export const UPDATE_FAMILY_CAR = 'UPDATE_FAMILY_CAR'
export const REMOVE_FAMILY_CAR = 'REMOVE_FAMILY_CAR'
export const ADD_MEMBER = 'ADD_MEMBER'
export const REMOVE_MEMBER = 'REMOVE_MEMBER'

export const SET_REFUELINGS = 'SET_REFUELINGS'
export const ADD_REFUELING = 'ADD_REFUELING'
export const UPDATE_REFUELING = 'UPDATE_REFUELING'
export const REMOVE_REFUELING = 'REMOVE_REFUELING'