name: Build

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build_push-image
        run: |
          echo ${{ secrets.ENV }} >> .env
          docker login -u ${{ secrets.LOGIN }} -p ${{ secrets.PASS }}
          docker build . -f ./Dockerfile -t ${{ secrets.ACR }}/${{ secrets.APPLICATION }}:latest
          docker push ${{ secrets.ACR }}/${{ secrets.APPLICATION }}:latest
          echo "Deploy successfully!"
      - id: auth
        name: Auth GCP
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: Update cluster
        run: |-
          gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER }} --zone ${{ secrets.GKE_ZONE }} --project ${{ secrets.GKE_PROJECT }}
          kubectl get pods -n default --no-headers=true | awk '/frontend-app/{print $1}'| xargs  kubectl delete -n default pod
